// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'disable',
    'aws_auth_facebook': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:acd29023-b7f6-4edd-b11c-e0fdb8c4bc61',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'grancentralmvp-hosting-mobilehub-806911104',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2v1ux23gykpi7.cloudfront.net',
    'aws_facebook_app_id': '325521941271540',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_google_app_permissions': 'email,profile,openid',
    // 'aws_mobile_analytics_app_id': 'd6bff822454e4342b4fe97c5829aa022',
    // 'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '3bfcbdb3-45fc-4cf9-a3f2-8ec61282ed89',
    'aws_project_name': 'grancentral-mvp-2018-06-13',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'grancentralmvp-mobilehub-806911104',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'grancentralmvp-userfiles-mobilehub-806911104',
    'aws_user_files_s3_bucket_region': 'us-west-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_z4KafjehR',
    'aws_user_pools_web_client_id': '6f47k7jkmenodti1207piufoar',
    'aws_appsync_graphqlEndpoint': 'https://ieegfdmqwbfuppypusfrivcxye.appsync-api.us-west-2.amazonaws.com/graphql',
    'aws_appsync_region': 'us-west-2',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
