// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_auth_facebook': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:26c2f869-fa51-4bff-92d7-e03aa45f8c22',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'grancentralmvp-hosting-mobilehub-1123545691',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dx8dxzpaxnpa0.cloudfront.net',
    'aws_facebook_app_id': '325521941271540',
    'aws_facebook_app_permissions': 'public_profile',
    'aws_google_app_permissions': 'email,profile,openid',
    'aws_mobile_analytics_app_id': '6f6e825d2c1f4fcb9063938d96ee02a1',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '4eb8b899-bc2c-44b5-b8b7-f925fd26e269',
    'aws_project_name': 'grancentral-mvp',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'grancentralmvp-mobilehub-1123545691',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'grancentralmvp-userfiles-mobilehub-1123545691',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_BNiYyFDeD',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '2gmaeoe97rv6o61006g3mp1hqu',
    'aws_appsync_graphqlEndpoint': 'https://gvu3cpw3lrf2xfenp65mtekg2m.appsync-api.us-east-2.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-2',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
